### ISSUE TITLE
[BUG] - Eventos externos não funciona

### ISSUE THREAD

**Issue by andre-lc-ferreira** [pedrodalvy/nestjs-rabbitmq-example#11]
# Qual o problema?

Se você rodar a aplicação comunicando nest com nest vai funcionar perfeitamente. O problema é quando se tenta disparar um evento que venha do proprio amqp usado o amqplib, para disparar o evento.

![image](https://user-images.githubusercontent.com/46267619/172650530-76a4eb48-6fdb-4252-a415-f7f85100686d.png)

![image](https://user-images.githubusercontent.com/46267619/172651013-71746e11-e06d-4cfd-9d16-ec9ccb5e3418.png)

Você sabe de alguma outra forma de executar isso vindo de aplicações externas? Pois creio que seja uma limitação do proprio nest.

**Comment by pedrodalvy** [comment]
Bom dia @andre2l2, desculpe não ter respondido antes, mas eu criei esse projeto apenas para praticar o que estava na doc do NestJs, nunca usei dessa forma que vc está tentando.

Percebi que o pacote [@golevelup/nestjs-rabbitmq](https://www.npmjs.com/package/@golevelup/nestjs-rabbitmq) funciona melhor para esses casos, você pode dar uma olhada nele se ainda não conseguiu resolver o problema.

Eu havia criado um projeto com um pouco mais de recursos para esse pacote do golevelup, mas não criei nem mesmo uma documentação pra ele. Se quiser pode dar uma olhada nele no repositório https://github.com/pedrodalvy/blog-microservices

**Comment by andre-lc-ferreira** [comment]
Seu projéto me ajudou muito a resolver um problema que estava tendo! E não se precupa com demora não, as conversãs assíncrona são as melhores kkkk. 

Mas sobre esse MessagePattern que o nest usa para consumir as filas, tem que ser em um formato especifico:

```json
{ "patter": "patter-name", "data": {  } }
```

Tendo que ter um patter dentro do que voce quer enviar, e isso estava me mostrando um erro. Mas no fim descobri que o problema, e era apenas isso, e deu tudo certo!

Muito obrigado!
